# Generated by Django 4.1.2 on 2022-11-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Geoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundary',
            name='ClosingEasting',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boundary',
            name='ClosingNorthing',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boundary',
            name='Easting1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boundary',
            name='Easting2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boundary',
            name='Easting3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boundary',
            name='Easting4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boundary',
            name='Northing1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boundary',
            name='Northing2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boundary',
            name='Northing3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boundary',
            name='Northing4',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
