# Generated by Django 4.1.2 on 2022-11-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Geoapp', '0002_alter_boundary_closingeasting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundary',
            name='ParcelId',
            field=models.IntegerField(unique=True),
        ),
    ]
