# Generated by Django 4.1.2 on 2022-11-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Geoapp', '0004_rename_closingeasting_boundary_easting5_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundary',
            name='OwnerPhoto',
            field=models.ImageField(upload_to='OwnerImage'),
        ),
    ]
