from django.db import models
class Boundary(models.Model):
    First_Name = models.CharField(max_length=100)
    Surname = models.CharField(max_length=100)
    Region = models.CharField(default = 'none',max_length=100)
    District = models.CharField(default = 'none',max_length=100)
    Locality = models.CharField(default = 'none',max_length=100)
    OwnerPhoto=models.ImageField(upload_to='OwnerImage')
    ParcelSizeInAcres=models.FloatField(default = 0)
    ParcelId = models.IntegerField(unique=True)
    Northing1 =models.FloatField(null=True,blank=True)
    Easting1 =models.FloatField(null=True,blank=True)
    Northing2 =models.FloatField(null=True,blank=True)
    Easting2 =models.FloatField(null=True,blank=True)
    Northing3 =models.FloatField(null=True,blank=True)
    Easting3 =models.FloatField(null=True,blank=True)
    Northing4 =models.FloatField(null=True,blank=True)
    Easting4 =models.FloatField(null=True,blank=True)
    Northing5 = models.FloatField(null=True,blank=True)
    Easting5 = models.FloatField(null=True,blank=True)